### ISSUE TITLE
Verify all OIDC id tokens in client mode (applies to all grant flows)

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#107]

**Comment by MartinFlores751** [comment]
OpenID ID Token validation should perform the following checks outlined in the OpenID Connect Core spec: https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

I'm thinking we can use or directly merge the checks with the local validation code, and pass in another variable to signify what token type we wish to verify (access token vs id token).

Since client mode does not use the access tokens, we should be able to ignore them.

**Comment by korydraughn** [comment]
So based on the token type, we change what is checked?

That sounds reasonable as long as it doesn't confuse us in the future.

Does this seem doable for 0.5.0?

**Comment by MartinFlores751** [comment]
> So based on the token type, we change what is checked?

Yes.

> Should we keep this in 0.5.0 or bump it to the next milestone?

We can keep this in 0.5.0.

---

Some OpenID Providers may not fully follow the OpenID specification regarding ID Token secrets. See keycloak/keycloak#13823.

We will provide an option, `non_standard_id_token_secret`, that allows for specifying the symmetric key secret for an ID Token.
