### ISSUE TITLE
Name of the package contains `experimental` 

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#159]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I tried to build the package.

### Expected behavior
The package name (rpm) is not `irods-client-http-api-0.1.0-1.el8.x86_64.rpm` but `irods-experimental-client-http-api-0.1.0-1.el8.x86_64.rpm`.

### Observed behavior (including steps to reproduce, if applicable)
https://github.com/irods/irods_client_http_api/blob/38d67aa5ab798952450dc4429c20d82586a375e8/CMakeLists.txt#L106

**Comment by korydraughn** [comment]
The use of **experimental** is intended. It was added as a hint to the admin that things can change in big ways depending on what we learn from usage of the application.

At the moment, there are no plans to publish packages for this project on packages.irods.org. We plan to make it available via Docker Hub only for now.

Since you're compiling from source, feel free to change the package name if you like.

**Comment by korydraughn** [comment]
The version number captures the fact that the HTTP API is experimental _(i.e. the interface isn't stable and may experience changes)_. Therefore, removal of the word, experimental, from the package name makes sense.
