### ISSUE TITLE
Consider changing parameter name from `no-trash` to `use-trash`

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#2]

**Comment by trel** [comment]
i like a positive option, rather than a negative one.

default would be `use-trash=1`.

**Comment by korydraughn** [comment]
My only gripe with changing to `use-trash` is the word `use`.

It feels weird to me. I'll try and explain.

When I run `irm -f`, I read that in two ways:
- Delete the data object permanently
- Delete the data object and **don't put it in the trash**
  - The text in bold translate to the `no-trash` option must better IMO
  - I feel `no-trash` also matches how people think about this _(I have no evidence for this either :-) )_

I feel `use` doesn't convey how people read/interpret removal well. I also don't have a better alternative that includes the word `trash`.

How do you feel about `permanent=0` or `permanently=0`? (not sure I like the `ly`)

Here's an idea.

What if we just offered two operations?
- `op=remove` _(this moves things to trash collection)_
- `op=remove_permanently` _(this does what you think)_

The downside is that there would be two remove operations. While is clean, it still feels off to me.

**Comment by trel** [comment]
well, we're stuck with the `trashcan` metaphor in the server and in the logical namespace and the rules and the microservices... so leaving it out feels like a confusion-trap as well.  hmm....

`no-trash` is fine for the reasons you say.     or... perhaps `--skip-trash`?   meh.

**Comment by mstfdkmn** [comment]
Wondering naively... Why isn't just `force` considered? Like in other clients and relevant msis, force positive - `'force=1'`- deletes permanently (meaning no-trash=1).

**Comment by korydraughn** [comment]
No one mentioned that as a possibility and `no_trash` is what is used by the C++ filesystem lib.

We'll consider `force` moving forward though.

**Comment by alanking** [comment]
After some more thought and deliberation... `no-trash` actually conveys the intent of the option in the clearest and most concise way. I think it's fine the way that it is.

**Comment by trel** [comment]
agreed.   i think we're okay to close this.

**Comment by alanking** [comment]
For future @alanking...

The *reason* `no-trash` conveys this the best way - despite having a negation in the name - is because we are instructing the API to bypass the server-defined trash policy. The positive alternative would be `use-trash`, but this isn't necessarily correct - the server could be configured to not use a trash can (i.e. data is surprisingly gone!). Another way to convey this would be express intent to delete the underlying data no matter what, but what is this really saying? We want to request that the server bypass the trash policy. So, we are really wanting to `bypass-trash-policy` and delete the data along with the catalog entry. This could be put more concisely as `no-trash`.
